global:
  scrape_interval:     15s
  external_labels:
    monitor: 'monitoring'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100'
