global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'monitoring'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets:
        - node-exporter:9100
        - localhost:9090

  - job_name: 'spine-a1a'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 145.136.246.202:9100

  - job_name: 'spine-a1b'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 145.136.246.226:9100

  - job_name: 'fw-a2a'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 145.136.246.221:9100

  - job_name: 'fw-a2b'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 145.136.246.222:9100

  - job_name: 'museum'
    scrape_interval: 5s
    file_sd_configs:
      - files: ['museum.yml']
