global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'monitoring'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'node'

  scrape_interval: 5s

  static_configs:
      - targets:
        - node-exporter:9100
        - cadvisor:8080
        - localhost:9090
